### ISSUE TITLE
minor bug: tdi_T1.mif

### ISSUE THREAD

**Issue by chrisvriend** [BIDS-Apps/MRtrix3_connectome#107]
I stumbled upon a minor but consequential bug in the script when verbosity >=2
the participant module of the script creates tdi_T1.mif in the scratch directory but after completing all the steps it wants to copy tdi_t1.mif (small t) to the output directory which does not exist.

**Comment by Lestropie** [comment]
Hi @chrisvriend,

This has already been fixed in 2433a906 (#100 / #104), but I am yet to merge the `hotfix` branch into `master` and release version 0.5.1. Unfortunately I'm so overloaded with other roles that this little side project is persistently neglected. But I'll try to get that done soon while there are less people demanding things of me.

Cheers
Rob
