### ISSUE TITLE
[BUG] Compromised credentials

### ISSUE THREAD

**Issue by effigies** [bids-apps/MRtrix3_connectome#121]
### Describe your problem in detail.

CircleCI has alerted everyone to cycle credentials stored in their environment variables: https://circleci.com/blog/january-4-2023-security-alert/

This project has what I suspect are @Lestropie's docker credentials in its environment variables.

**Comment by Lestropie** [comment]
Thanks for the heads-up.

Rotated the GitHub OAuth tokens, even though apparently CircleCI has done so for all users at their end.

My DockerHub password has been modified.
(Tags currently aren't automatically resulting in Docker image pushes because I've not invested the effort in getting the CI up to date; but the credentials needed to be cycled nevertheless)
