### ISSUE TITLE
How to specify -rpe_none for dwipreproc?

### ISSUE THREAD

**Issue by seldamat** [BIDS-Apps/MRtrix3_connectome#23]
I was unable to run the docker container out of the box :(

I executed 
`docker run -i --rm -v /Users/admin/Anvil/sync/datasets/adolescent-development-study/mris.bids:/bids_dataset -v /Users/admin/Anvil/sync/datasets/adolescent-development-study/derivatives/mritrix-connectome:/outputs bids/mrtrix3_connectome /bids_dataset /outputs participant --debug --parcellation fs_2005`

And received the error
```
run.py: [DEBUG] run.exeName() (from run.py:53): bids-validator -> bids-validator
run.py: [DEBUG] run.versionMatch() (from run.py:338): Command bids-validator not found in MRtrix3 bin/ directory
run.py: [DEBUG] run.exeName() (from run.py:340): bids-validator -> bids-validator
run.py: [DEBUG] run._shebang() (from run.py:54): File "bids-validator": string "#!/usr/bin/env node": ['/usr/bin/env', 'node']
run.py: [DEBUG] run.command() (from run.py:659): To execute: [['/usr/bin/env', 'node', '/usr/bin/bids-validator', '/bids_dataset']]
Command:  bids-validator /bids_dataset
run.py: Commencing execution for subject sub-001
run.py: [DEBUG] fsl.exeName() (from run.py:26): fsl5.0-flirt
run.py: [DEBUG] fsl.exeName() (from run.py:27): fsl5.0-fsl_anat
run.py: [DEBUG] fsl.suffix() (from run.py:28): NIFTI_GZ -> .nii.gz
run.py: Generated temporary directory: /run.py-tmp-YWW6SY/
run.py: [ERROR] Inadequate data for pre-processing of subject 'sub-001': No phase-encoding contrast in input DWIs or fmap/ directory
run.py: Contents of temporary directory kept, location: /run.py-tmp-YWW6SY/
```
This project did not collect phase-encoding contrasts (used an older siemens tim trio), so we cannot perform inhomogeneity field estimation.

Any ideas on how to proceed with the docker execution of this dataset? 

Thanks,
S

**Comment by Lestropie** [comment]
Hi Shady,

I like your Git profile bio :-P

Because this pipeline requires on the Anatomically-Constrained Tractography (ACT) framework, correction of EPI susceptibility distortions is a prerequisite. While we have a method currently under development for performing this correction using the subject's T1-weighted image (similar to [this method](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4461504/)), it is not yet in the public domain, and hence cannot be used in this script.

While EPI distortion correction using gradient-echo-based field mapping is not yet supported in the *MRtrix3* script `dwipreproc`, such data can in fact be used in conjunction with FSL's `eddy` tool, so this is one possibility that I may look into in the future. There are additionally other methods proposed for achieving such correction; if you have experience and/or recommendations for any particular approach, please forward any details you can.

We also have a manuscript in preparation demonstrating just how problematic connectome construction is if one does *not* use ACT (or a comparable framework), which will hopefully at least somewhat justify the outright error message.

Cheers
Rob

**Comment by Lestropie** [comment]
@seldamat: With the merge of version `0.3.0` of this App, I've made the limitation described above more clear in the [readme page](https://github.com/BIDS-Apps/MRtrix3_connectome). I've also made an explicit listing in this repository (#27) describing ways in which this limitation could be overcome; so any discussion or development on that front will be posted there.

**Comment by seldamat** [comment]
@Lestropie

Thanks for the support!! It is dizzying to see how quickly updates are being released for mrtrix3. I do not have any expertise to contribute to this but excited to stay abreast of developments and contribute where I can :)
