### ISSUE TITLE
Dockerhub is behind by 6 months 

### ISSUE THREAD

**Issue by dkp** [BIDS-Apps/MRtrix3_connectome#38]
It would be great if dockerhub build was updated.

**Comment by Lestropie** [comment]
The Dockerhub container is 6 months old because the App hasn't really been updated in 6 months :-/  I have a series of changes occurring in the main *MRtrix3* repository that will eventually need to be reflected in this App, but I've not been able to commit time to this App of late. Hopefully when I get back to completing the manuscript for this App I can add some outstanding things.

Regarding the original post:
```
Step 7/56 : RUN apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
---> Running in e363055aeefa
Executing: /tmp/apt-key-gpghome.nB2rGV2iyT/gpg.1.sh --recv-keys --keyserver pgp.mit.edu 2649A5A9
gpg: keyserver receive failed: No data
The command '/bin/sh -c apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9' returned a non-zero code: 2
```
This unfortunately occurs sporadically, and is usally solved by just re-running the build. I saw a trick in another repository where they store the required key data in a file within the repository and import it into the container during the build process; I will likely use the same technique in the future.

**Comment by dkp** [comment]
Hmm, as far as I can tell, the last dockerhub build reports being a year old, not 6 months old.
The dockerfile available for viewing on dockerhub uses ubuntu 14.04. However, the dockerfile here: https://github.com/BIDS-Apps/MRtrix3_connectome/blob/master/Dockerfile is using ubuntu 18.

**Comment by Lestropie** [comment]
I'm not quite sure what's going on there. Both 0.3.0 and latest show as being 7 months old for me. But DockerHub doesn't seem to offer a great deal of control (at least from my account). I'll have a close look after pushing 0.4.0.

**Comment by Lestropie** [comment]
@dkp: Version 0.4.0 is [now up on DockerHub](https://hub.docker.com/r/bids/mrtrix3_connectome/tags). Changes described in #40.

It seems however that the [Dockerfile showing on the DockerHub website](https://hub.docker.com/r/bids/mrtrix3_connectome/dockerfile) is *still* out of date, i.e. is from an older version of the App, and I don't appear to have any control over that from within my DockerHub account. @chrisfilo: Have you encountered this previously? Any idea why the Dockerfile shown on the DockerHub website would not track the `:latest` tag?

**Comment by dkp** [comment]
I've pulled the image now and it updated a BUNCH of layers...(though I see a bunch of "failed" messages on dockerhub).  I've just told it to run with --debug mode on, and with --output_verbosity 3 but I am not sure what it is doing...I see no temp directory.  I tried running with --version and it did not return any info to the command line.

I'm new to this stuff, so my experiences are those of a novice.  Nevertheless, here are the problems I've dealt with getting dockerhub to behave :

1) I've had problems with the webhooks getting broken or corrupted (after I fooled around renaming and recreating the git repository on line).
2) AND I've had problems with the whole automated system producing corrupted builds of my project.  I had more success with manual builds like this:
push to the hub:
>docker login (enter credentials)
>docker tag bipbids diannepat/bipbids
>docker push diannepat/bipbids
