### ISSUE TITLE
dwipreproc fails

### ISSUE THREAD

**Issue by araikes** [BIDS-Apps/MRtrix3_connectome#42]
I started running a single subject as test for this app using the newest version (version 0.4.0). I have a single DWI image in my sub/dwi folder and a single reverse phase-encoded EPI in the sub/fmap folder. The process appears to run fine for the denoising and deringing. Additionally, the program splits the concatenated dwi and rpe image:

```
mrconvert /bids_dataset/sub-168/dwi/sub-168_run-01_dwi.nii -fslgrad /bids_dataset/sub-168/dwi/sub-168_run-01_dwi.bvec /bids_dataset/sub-168/dwi/sub-168_run-01_dwi.bval -json_import /bids_dataset/sub-168/dwi/sub-168_run-01_dwi.json /output/mrtrix3_connectome.py-tmp-45ONXG/dwi1.mif
mrconvert /bids_dataset/sub-168/fmap/sub-168_run-01_dir-PA_epi.nii -json_import /bids_dataset/sub-168/fmap/sub-168_run-01_dir-PA_epi.json -set_property dw_scheme "0,0,1,0\n0,0,1,0" /output/mrtrix3_connectome.py-tmp-45ONXG/fmap1.mif
mrconvert /bids_dataset/sub-168/anat/sub-168_run-01_T1w.nii /output/mrtrix3_connectome.py-tmp-45ONXG/T1.mif
mrcat fmap1.mif dwi1.mif dwi_fmap_cat.mif -axis 3
dwidenoise dwi_fmap_cat.mif dwi_fmap_cat_denoised.mif
mrdegibbs dwi_fmap_cat_denoised.mif dwi_fmap_cat_denoised_degibbs.mif -nshifts 50
mrconvert dwi_fmap_cat_denoised_degibbs.mif se_epi.mif -coord 3 0:1
mrconvert dwi_fmap_cat_denoised_degibbs.mif dwipreproc_in.mif -coord 3 2:51
os.makedirs('eddyqc')
```

However, the following error occurs when the process advances to preproc:
```
dwipreproc: Loading header for image file 'dwi.mif' 
dwipreproc: Loading header for image file 'se_epi.mif'
dwipreproc: [ERROR] No diffusion gradient table found
```
If I do `mrinfo` on dwi.mif and se_epi.mif, they both have the same information and it's for the reverse phase-encoded image. I can confirm that the original images have different .json files and are indeed different images.

It seems as though part of the header info from the original dwi image got lost in the process. Is there a way to fix this or coerce dwipreproc to load the correct json??

**Comment by Lestropie** [comment]
Hi @araikes,

Thanks for the report. Certainly from the outputs you've provided there doesn't seem to be anything untoward: the second `mrconvert` call manually inserts a diffusion gradient table for the two spin-echo volumes in the solitary `fmap/` image, and both the `mrcat` and `mrconvert` calls should respectively concatenate & split the diffusion gradient table in the header(s) between DWI and dedicated spin-echo images.

Maybe first: are you running the tool within the prescribed container, or are you using the script file as a standalone executable running against a manually-installed version of *MRtrix3*? If the latter, there's a chance that even if your version of the script is near-new (I just pushed 0.4.1, but it doesn't have any changes from 0.4.0 that should be relevant to your specific issue), if your *MRtrix3* installation is old, there may be a past issue that's preventing the appropriate gradient table handling from working internally within those commands (e.g. `mrcat` using the gradient table of the first input image rather than concatenating the two tables as it should).

You could also try running the script while specifying the debug option, and we'll see if that gives any hints.

I'll have a go at reproducing the issue with some data of my own; but if I'm unable to do that, and using the debug option doesn't yield any insight, I might see about grabbing some example data from you to see if I can reproduce the issue that way.

Cheers
Rob

**Comment by araikes** [comment]
Hi Rob,
I used the docker container as described with the debug option (`-debug 3`). I'm dropping the available log files in here but they didn't appear to be terribly informative, aside from what I sent. Again, the weirder thing, in my observation is the fact that both the input and se image after the split have the same `mrinfo` output.

[error.txt](https://github.com/BIDS-Apps/MRtrix3_connectome/files/2943010/error.txt)
[log.txt](https://github.com/BIDS-Apps/MRtrix3_connectome/files/2943011/log.txt)

**Comment by Lestropie** [comment]
OK, I think I've found the issue by replicating your particular use case and running with the `--debug` flag. Specifically [here](https://github.com/BIDS-Apps/MRtrix3_connectome/blob/0.4.1/mrtrix3_connectome.py#L240-L242), where I have to manually insert a diffusion gradient scheme to any images in the `fmap/` directory, so that when `mrcat` / `mrconvert` are called the tables are appropriately concatenated / split. If the `fmap/` image contains more than one volume, the script needs to insert a multi-line gradient table into the header of that image, but that is currently not working correctly. For a 4D image with two volumes like in your example, this is being read by the *MRtrix3* binaries as a 1x7 matrix rather than a 2x4 matrix. This therefore prevents `mrcat` from concatenating this with the DWI gradient table due to the mismatch in number of columns.

If you want to proceed with your data immediately, splitting the 4D image into two 3D images, each with its own JSON, *should* work. On my end I'll need to figure out why the newline in that fake gradient table isn't propagating correctly, and push out a hotfix.

**Comment by ajdneuro12** [comment]
Hello,

Thanks for this great resource! I had a similar issue, I am running it with the latest docker image. I am getting the error that no phase encoding information is being found in my DWI but I checked the jsons and it is there and it works when I do it outside of the docker image, running mrtrix locally. Thank you! Attached is the output of the debug command. 
[error.txt](https://github.com/BIDS-Apps/MRtrix3_connectome/files/2974676/error.txt)

**Comment by Lestropie** [comment]
@ajdneuro12: I'm not sure whether or not your issue has the same cause as that reported here. Your JSON files appear to contain a LOT of information from the source DICOMs, but the phase encoding information may not have been written with the appropriate BIDS key names. You could try making the code modifications in #43 locally and see if the script then succeeds with your data; otherwise I would suggest posting the JSON files you have in case that is the source of your issue.

**Comment by ajdneuro12** [comment]
Hi @Lestropie, 

Thanks for your response, I can't quite figure it out. The JSON is attached, any ideas? Thanks again!
[sub-NDARINV1EECRFPM_ses-baselineYear1Arm1_dwi.json.txt](https://github.com/BIDS-Apps/MRtrix3_connectome/files/2975854/sub-NDARINV1EECRFPM_ses-baselineYear1Arm1_dwi.json.txt)

**Comment by Lestropie** [comment]
Okay, that particular file looks fine: Both "`TotalReadoutTime`" and "`PhaseEncodingDirection`" are in there. However I saw in your earlier log file that "`PhaseEncodingDirection`" was absent from image headers, and "`PhaseEncodingDirectionPositive`" was present: the latter is a Siemens private field that would typically be utilised in the calculation of the former, but then discarded. So it would be worth cross-checking the JSON files of your `fmap/` images also, to make sure that these fields are correct.

**Comment by ajdneuro12** [comment]
Hi @Lestropie,

You were correct, I regenerated the json's for the fmaps and made sure they had the PhaseEncodingDirection and dwipreproc is running now. Thanks!

Alex

**Comment by Lestropie** [comment]
:muscle:
