### ISSUE TITLE
Non-empty fmap folders

### ISSUE THREAD

**Issue by araikes** [BIDS-Apps/MRtrix3_connectome#67]
It's possible that fmap folders exist for fMRI sequences but don't contain an RPE file for DWI. This line 622 (dev_reformat) should probably contain some logic that flags either the nonexistence of the fmap folder (currently implemented with the `elif`) or `len(fmap_image_list) == 0` as well as the other logic. Otherwise it is possible to run to completion without actually having the RPE file.

https://github.com/BIDS-Apps/MRtrix3_connectome/blob/33cbd7474af59983bf91e8862103857ba6d93477/mrtrix3_connectome.py#L622

**Comment by Lestropie** [comment]
Sorry, I'm having trouble disentangling precisely what the issue seems to be on this one. The logic here is that if the BIDS data do not contain any spin-echo EPIs in the `fmap/` directory, it may still be possible for the script to proceed: if the `dwi/` directory contains more than one series, it is possible that those series may have been acquired using different phase encoding directions; in that case `dwipreproc` will be run *without* the `-se_epi` option, instead automatically extracting the *b*=0 images from the DWIs and providing those to `topup`. The magic of trying to process any type of data that a user may provide is kind of a shared effort between the contents of this script and *MRtrix3*'s `dwipreproc`...

I think this issue might just be a case of a certain type of DWI acquisition protocol that you may not have thought of?

**Comment by araikes** [comment]
Thinking about this from an automated one-touch sort of running script, I'll give you a use-case example (that is in fact running right now in a terminal):

I have a participant for whom we have a T1w, a single DWI (1 run, A->P), and rs-fMRI. With the rs-fMRI we collected field maps (mag1, mag2, phasediff). These get placed in the `fmap/` folder. We were supposed to collect a RPE scan (P->A) but for whatever reason we didn't for this individual (or the file is missing) However, the rest of the data is good to go.

If I've understood the general theory of the code (and your post) correctly, when I run this script it **should** fail on this person because the RPE file isn't there and the DWI sequence is only one direction (A->P). However, we are on `eddy` right now without the `se_epi` option enabled.

My assumption from the `if/elif` logic linked above is that it will only fail if the `fmap/` folder is missing _**and**_ there are fewer than two files in the `dwi/` folder. However, in this case, there is an `fmap/` folder and so it runs anyway even without the phase different PE directions.

**Comment by Lestropie** [comment]
Okay, I think I follow the logic now. Basically, when determining whether or not there are adequate image data to proceed, that decision should be informed based on the *number of SE-EPI images* found in the `fmap/` directory and the number of DWI series, whereas currently it is based on the *presence of the* `fmap/` `*directory* and the number of DWI series. In your specific case that distinction makes a difference. That's actually a pretty simple fix.

Ideally the multi-gradient-echo data would instead be used; that would then require I think *removing* the `IntendedFor` field from the `fmap/` JSON such that the field map data can be used for either DWI or fMRI distortion correction. This has however been low on my todo list for quite a while now.
