### ISSUE TITLE
dockerhub update?

### ISSUE THREAD

**Issue by dkp** [BIDS-Apps/MRtrix3_connectome#84]
Hi Robert,

I know you have set yourself a lot of tasks to make this container perfect.  
I am, however, teaching a class on Neuroimaging this semester, and I wanted to introduce MRtrix3_connectome on the last day (12/1/2020).  Is there any chance that there will be a new container to pull by then?  Or should we just use the existing one?
(Or is it worth it to download the current GitHub project and build from that?)

I would appreciate your advice.

-Dianne Patterson

**Comment by Lestropie** [comment]
Yes you're right, my poor side project is being neglected because I forget that other people might actually want to use it... Plus now I'm getting beaten to publication by all of these DWI pre-processing apps ><

I'll try to resolve what's already in place, do some testing, merge #62 and tag. Main thing I still wanted to sort out was #74, but included in that code branch is trying to support pre-existing freesurfer derivatives, and that introduces all sorts of weird code branches depending on parcellation choice; so I might have to delay that one.

**Comment by dkp** [comment]
I understand...it IS a cool project though, and it makes MRTrix results available to folks who have not yet waded through the details of MRtrix. I would not have found the time to wade into MRtrix without your project. You provide the gateway drug ; )
For the class, they'll likely have their data processed with fMRIprep (most recent LTS version), so that is the most likely source of a Freesurfer directory. Thanks for creating the project...and finding time to work on it.

**Comment by Lestropie** [comment]
@dkp: The `0.5.0` tag now [appears on DockerHub](https://hub.docker.com/layers/bids/mrtrix3_connectome/0.5.0/images/sha256-84a9d4be8686b025bf6949c6067d7cf8f48fbd535d9bd8acc0a8ac6e0996b28b?context=explore).
